// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2dJ3gBERnd671FPvCJb3f4j_ZRTuxjXY',
    appId: '1:1079801214142:web:f78e3c5eac7ca1001b1aef',
    messagingSenderId: '1079801214142',
    projectId: 'volvo-358a4',
    authDomain: 'volvo-358a4.firebaseapp.com',
    databaseURL: 'https://volvo-358a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'volvo-358a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW3YEZ5WP0omtUMfDdK3XSoON_EZQqMpI',
    appId: '1:1079801214142:android:9f938be72132eb821b1aef',
    messagingSenderId: '1079801214142',
    projectId: 'volvo-358a4',
    databaseURL: 'https://volvo-358a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'volvo-358a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrOBoZ5gyA71G5Ktb1SqB6WnXsZsrCRso',
    appId: '1:1079801214142:ios:14df935e9cd89aa51b1aef',
    messagingSenderId: '1079801214142',
    projectId: 'volvo-358a4',
    databaseURL: 'https://volvo-358a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'volvo-358a4.appspot.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrOBoZ5gyA71G5Ktb1SqB6WnXsZsrCRso',
    appId: '1:1079801214142:ios:14df935e9cd89aa51b1aef',
    messagingSenderId: '1079801214142',
    projectId: 'volvo-358a4',
    databaseURL: 'https://volvo-358a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'volvo-358a4.appspot.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2dJ3gBERnd671FPvCJb3f4j_ZRTuxjXY',
    appId: '1:1079801214142:web:9b26999840bb3a3b1b1aef',
    messagingSenderId: '1079801214142',
    projectId: 'volvo-358a4',
    authDomain: 'volvo-358a4.firebaseapp.com',
    databaseURL: 'https://volvo-358a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'volvo-358a4.appspot.com',
  );

}